trigger:
- main

stages:

- stage: AndroidStage
  pool:
    name: Default
  dependsOn: []
  displayName: Android
  jobs:
 

  - job: APK
    displayName: Android
    steps:

    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'
     
    - task: FlutterCommand@0
      displayName: "Run Flutter diagnostics"
      inputs:
        projectDirectory: '.'
        arguments: 'doctor -v'

    - task: FlutterBuild@0
      displayName: 'Flutter Build apk'
      inputs:
        target: apk
        projectDirectory: '$(Build.SourcesDirectory)'
        debugMode: false

    - task: FlutterTest@0
      displayName: "Run unit tests"
      inputs:
        generateCodeCoverageReport: true
        projectDirectory: '$(Build.SourcesDirectory)'

    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: false       

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
       
    - task: PublishBuildArtifacts@1
      displayName: "Publish AAB file"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'AAB'
        publishLocation: 'Container'
      
    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'AppCenter'
        appSlug: 'kapalulz'
        appFile: '**/*.apk'
        symbolsOption: 'Android'
        releaseNotesOption: 'input'
        releaseNotesInput: 'tetst'
        destinationType: 'groups'
        distributionGroupId: 'Beta Testers'