# Flutter build
variables:
  projectDirectory: 'covid_19_tracker'
trigger:
- main
jobs:
  - job: Android
    pool:
      name: Default
    steps:
    - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0 
      displayName: 'Flutter Install'
      inputs:
        version: custom
        customVersion: 1.22.6
    
    - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
      displayName: 'Flutter Build apk'
      inputs:
       projectDirectory: 
       debugMode: true // remove if a release build
       buildFlavour: development
       entryPoint: 'lib/main_dev.dart'
       apkTargetPlatform: 'android-arm64'
  
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: false

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1