# Flutter build
variables:
  projectDirectory: 'covid_19_tracker'
trigger:
- main
jobs:
  - job: Android
    pool:
      name: Default
    steps:
    - task: FlutterInstall@0 
      displayName: 'Flutter Install'
      inputs:
        version: custom
        customVersion: 1.22.6
     
    - task: Hey24sheep.flutter.flutter-command.FlutterCommand@0
      displayName: "Run Flutter diagnostics"
      inputs:
        projectDirectory: '.'
        arguments: 'doctor -v'

    - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
      displayName: "Build application"
      inputs:
        target: 'aab'
        projectDirectory: '$(Build.SourcesDirectory)'

    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: false

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1