pool:
  name: Default
  demands: SpecialSoftware # exists check for SpecialSoftware

variables:
  projectDirectory: 'myapp'
trigger:
- main
jobs:
  - job: Android
    pool:
      vmImage: 'ubuntu-latest'
